version: "3.8"
services:
  postgresql:
    build: postgresql
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
  bot:
    build: bot
    restart: unless-stopped
volumes:
  postgresql-data: